# Generated by Django 6.0 on 2026-03-20 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(50)])),
                ('descricao', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
