# Generated by Django 6.0 on 2026-03-20 23:59

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(80)])),
                ('dados_entrada', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('criado', models.DateTimeField(default=datetime.datetime(2026, 3, 20, 20, 59, 18, 571790))),
                ('atualizado', models.DateTimeField(default=datetime.datetime(2026, 3, 20, 20, 59, 18, 571815))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='online_judge.teste')),
                ('ordem', models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'abstract': False,
            },
            bases=('online_judge.teste',),
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('teste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='online_judge.teste')),
                ('peso', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'abstract': False,
            },
            bases=('online_judge.teste',),
        ),
    ]
