# Generated by Django 6.0 on 2026-03-21 00:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0002_teste_caso_exemplo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 20, 21, 9, 24, 801157)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 20, 21, 9, 24, 801132)),
        ),
    ]
