# Generated by Django 6.0 on 2026-03-22 19:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0003_alter_categoria_slug_alter_teste_atualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('compilador', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(5)])),
                ('versao', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('multiplicador_tempo', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('multiplicador_memoria', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('codigo_fonte', models.TextField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.TextField(choices=[('NOT_ANSWERED', 'Não Respondida'), ('IN_QUEUE', 'Em fila de execução'), ('RUNNING', 'Execução'), ('ACCEPTED', 'Aceito'), ('WRONG_ANSWER', 'Resposta Errada'), ('TIME_LIMIT_EXCEEDED', 'Tempo Limite Excedido'), ('MEMORY_LIMIT_EXCEEDED', 'Limite de Memória Excedido'), ('RUNTIME_ERROR', 'Erro de Runtime'), ('COMPILATION_ERROR', 'Erro de Compilação'), ('PRESENTATION_ERROR', 'Erro de Apresentação'), ('INTERNAL_ERROR', 'Erro Interno')])),
                ('submetido', models.DateTimeField()),
                ('avaliado_em', models.DateTimeField()),
                ('tempo_execucao_ms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('memoria_utilizada_kb', models.IntegerField(validators=[django.core.validators.MinValueValidator(32)])),
                ('nota', models.IntegerField(choices=[(100, '100'), (150, '150'), (200, '200'), (250, '250'), (300, '300'), (400, '400'), (500, '500'), (600, '600'), (800, '800'), (1000, '1000')])),
                ('log_execucao', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 16, 57, 47, 669165)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 16, 57, 47, 669165)),
        ),
    ]
