# Generated by Django 6.0 on 2026-03-22 20:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0004_linguagem_submissao_alter_teste_atualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descricao', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(5)])),
                ('url', models.URLField(null=True)),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField()),
                ('freeze', models.DateTimeField()),
                ('publico', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 12, 21, 821189))),
                ('atualizado', models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 12, 21, 821189))),
                ('penalidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 12, 21, 803983)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 12, 21, 803983)),
        ),
    ]
