# Generated by Django 6.0 on 2026-03-22 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0005_competicao_alter_teste_atualizado_alter_teste_criado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 14, 779233)),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 14, 779233)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 14, 771635)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 14, 771635)),
        ),
    ]
