# Generated by Django 6.0 on 2026-03-22 20:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0006_alter_competicao_atualizado_alter_competicao_criado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('pontos', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ordem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='competicao',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 43, 118971)),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 43, 118971)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 43, 104029)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 17, 17, 43, 104029)),
        ),
    ]
