# Generated by Django 6.0 on 2026-03-22 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0007_problemacompeticao_alter_competicao_atualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 21, 29, 148394)),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 21, 29, 148394)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 21, 29, 117146)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 21, 29, 117146)),
        ),
    ]
