# Generated by Django 6.0 on 2026-03-22 21:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0008_alter_competicao_atualizado_alter_competicao_criado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2016, 3, 22))])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('genero', models.TextField(choices=[('MAN', 'Homem'), ('WOMAN', 'Mulher'), ('NON_BINARY', 'Não binário'), ('NOT_INFORMED', 'Não informado')])),
                ('pagina_pessoal', models.URLField(max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('biografia', models.TextField(null=True)),
                ('idioma', models.TextField(choices=[('PT_BR', 'Português do Brasil'), ('EN_US', 'Inglês dos EUA'), ('ES_ES', 'Espanhol da Espanha')])),
                ('premium', models.BooleanField(default=False)),
                ('membro_desde', models.DateField(default=datetime.date(2026, 3, 22))),
                ('instituicao', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)])),
                ('posicao_ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('resolvidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submetidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('treinador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='competicao',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 29, 54, 60964)),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 29, 54, 60964)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 29, 54, 44140)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 29, 54, 44140)),
        ),
    ]
