# Generated by Django 6.0 on 2026-03-22 21:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0009_perfil_alter_competicao_atualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('enunciado', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('enunciado_entrada', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('enunciado_saida', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('dificuldade', models.CharField(choices=[(1, 'Muito Fácil'), (2, 'Fácil'), (3, 'Básico'), (4, 'Intermediário'), (5, 'Intermediário Alto'), (6, 'Difícil'), (7, 'Muito Difícil'), (8, 'Avançado'), (9, 'Muito Avançado'), (10, 'Perito')])),
                ('idioma', models.CharField(choices=[('PT_BR', 'Português do Brasil'), ('EN_US', 'Inglês dos EUA'), ('ES_ES', 'Espanhol da Espanha')])),
                ('fonte', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)])),
                ('limite_tempo_ms', models.CharField(choices=[(1000, '1 segundo'), (2000, '2 segundos'), (3000, '3 segundos'), (4000, '4 segundos'), (5000, '5 segundos'), (6000, '6 segundos'), (7000, '7 segundos'), (8000, '8 segundos'), (9000, '9 segundos'), (10000, '10 segundos')], default=1000)),
                ('limite_memoria_mb', models.CharField(choices=[('8', '8 MB'), ('16', '16 MB'), ('32', '32 MB'), ('64', '64 MB'), ('128', '128 MB'), ('256', '256 MB')], default='32')),
                ('publico', models.BooleanField(default=True)),
                ('nota', models.IntegerField(choices=[(100, '100'), (150, '150'), (200, '200'), (250, '250'), (300, '300'), (400, '400'), (500, '500'), (600, '600'), (800, '800'), (1000, '1000')])),
                ('criado', models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 45, 24, 127409))),
                ('atualizado', models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 45, 24, 127409))),
            ],
        ),
        migrations.AlterField(
            model_name='competicao',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 45, 24, 111787)),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 45, 24, 111787)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='atualizado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 45, 24, 96161)),
        ),
        migrations.AlterField(
            model_name='teste',
            name='criado',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 18, 45, 24, 96161)),
        ),
    ]
